- name: Create the cache directory
  ansible.builtin.file:
    path: '{{ cache_directory }}'
    state: directory
    mode: '0755'
  register: cachedir
  when: 'not zip_location'

- name: Compute saagiectl location
  ansible.builtin.set_fact:
    zip_location: '{{ cachedir.path + "/saagiectl-" + saagie_version + ".zip" }}'
  when: not zip_location

- name: Setting saagiectl install directory
  ansible.builtin.set_fact:
    saagie_install_directory: '{{ "saagiectl-" + saagie_version }}'

- name: Create the install directory
  ansible.builtin.file:
    path: '{{ (working_directory, saagie_install_directory) | join("/") }}'
    state: directory
    mode: '0755'

- include_tasks: linux.yml
  when: 'ansible_facts["os_family"] not in ["Darwin", "Windows"]'
- include_tasks: darwin.yml
  when: 'ansible_facts["os_family"] == "Darwin"'

- name: Unzip saagiectl
  ansible.builtin.unarchive:
    src: '{{ zip_location }}'
    dest: '{{ (working_directory, saagie_install_directory) | join("/") }}'
    remote_src: yes
    list_files: yes
  register: unzip
  failed_when: 'saagiectl not in unzip.files'

- name: Setting saagiectl path
  ansible.builtin.set_fact:
    saagiectl: '{{ saagie_install_directory }}/{{ saagiectl }}'

- name: Run saagiectl
  ansible.builtin.command:
    argv: '{{ [ saagiectl ] + item }}'
    chdir: '{{ working_directory }}'
  changed_when: true
  with_list: '{{ argv }}'

- include_tasks: patches/SRI-724.yml
  when: http_proxy or https_proxy